apiVersion: v1
kind: Service
metadata:
  name: s1
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  selector:
    app: sts2
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
