apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts2
spec:
  selector:
    matchLabels:
      app: sts2
  replicas: 3 # by default is 1
  serviceName: sts2
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: sts2
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: web2
          image: python:bullseye
          command:
            - "bash"
            - "-c"
            - "echo sleeping; sleep 30; /usr/local/bin/python -m http.server"
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
